name: PepsiDog
version: ${project.version}
main: me.arnoldsk.pepsidog.PepsiDog
api-version: 1.13
authors: [ArnoldsK]
description: Miscellaneous additions for Pepsi Dog server usage
website: https://pepsidog.lv
commands:
  opstick:
    description: Server operator command to get a stick that does everything
    usage: opstick
  whereis:
    description: Get the location of a player
    usage: whereis [player]
  talismanoflight:
    description: Get the recipe
    usage: talismanoflight
  magnet:
    description: Get the recipe
    usage: magnet
  imagemap:
    description: Get a map with the provided image URL
    usage: imagemap https://i.imgur.com/cat.png